### ISSUE TITLE
ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed. 

### ISSUE THREAD

**Issue by nicholasray** [wikimedia/pixel#112]
```
SCENARIO > QuickSurvey with multiple answers (#scroll #quicksurvey #minerva)
x Close Browser
ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
    at /usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:24
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:222:16)
    at ExecutionContext._evaluateInternal (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:155:21)
    at WaitTask.rerun (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:540:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This is an error I've been seeing in the pixel.wmcloud.org logs although I'm not sure if it's unique to quick surveys or it occurs in other tests

**Comment by nicholasray** [comment]
I've run ./pixel.js reference -b latest-release -c 830955 --group web-maintained locally and have also been able to replicate this with quick surveys so it might be specific to that test group

**Comment by jdlrobson** [comment]
Looks like we're using http in the default survey link. Bug in QuickSurveys?

	"ext-quicksurveys-example-external-survey-link": "https://example.org/survey",
